### PR TITLE
Issue76 kmeans

### PR DESCRIPTION
**Pull request by matteobsu**
#76 

Tested and works efficiently.

### CODE REVIEW

**Comment by matteobsu** [comment]
Maybe include example and instruction in the docs.

**Comment by JeanBilheux** [comment]
Can you guide us on how to test this branch?

**Comment by matteobsu** [comment]
> 
> 
> Can you guide us on how to test this branch?


How about I distribute a pdf of the notebook I used to code and test it? I used the usual data_E.mat dataset as reference.
[Fit-kmeans.pdf](https://github.com/neutronimaging/ToFImaging/files/5796936/Fit-kmeans.pdf)

I believe a view of the pdf and the code should be sufficient

**Comment by JeanBilheux** [comment]
Sounds good. You can even add it to this ticket. Do you have any unit test as well?

**Review by anderskaestner — APPROVED** [review]
Looks fine to me.

Just one little comment, have you considered using np.nan_to_num instead of 	    Tarray[np.isnan(Tarray)]=0
Tarray[np.isinf(Tarray)]=0

**Comment by matteobsu** [comment]
> 
> 
> Looks fine to me.
> 
> Just one little comment, have you considered using np.nan_to_num instead of Tarray[np.isnan(Tarray)]=0
> Tarray[np.isinf(Tarray)]=0

Hi,
I wasn't aware of nan_to_num. It seems that the version 1.17 is required to be utilizable in this script. This is because infinities are replaced with very big numbers that are still an issue  for the rest of the code.  But in the latest version you can set the infinity replacement value.
I'm afraid that this update will require users to update numpy :P

**Pull request merged**
